---
- hosts: neo
  become: True
  tasks:
    - name: Install python pip
      yum:
        name: pip
        state: present
    - name: Install docker
      yum:
        name: docker
        state: present
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
	
    - name: Install Kubernetes cluster
      shell:
	    sh 'base_setup.sh'
		sh 'master.sh'
		sh 'worker.sh'